### ISSUE TITLE
PHP expects ../vendor/ directory

### ISSUE THREAD

**Issue by n8willis** [ikr/annotator-store-lite#1]
Hi, just started playing around with this for a lightweight annotation project. Thanks for building something that doesn't require a colossal Java stack!

Hit an issue right at the beginning, though - the init_db.php script fails because it's looking for a "../vendor/" directory that will hold an autoload.php script. 

What's that for? It's apparently in the .gitignore and a quick search shows several other references to the same directory.

Just trying to understand!

**Comment by ikr** [comment]
Ah, right. `vendor` is created by [Composer](https://getcomposer.org/) — the PHP dependency manager. The problem should be as easy to fix as running `composer install` in the project root.
