### ISSUE TITLE
nginx configuration incomplete?

### ISSUE THREAD

**Issue by n8willis** [ikr/annotator-store-lite#2]
It seems like the 'sample config' for nginx shown in the README  is incomplete, somehow. Certainly, using it I can start up nginx and curl reports success on the installation root URL ... but it 404s when requesting /annotator-store-lite....

Are there, maybe, some assumptions made about how else nginx is configured? For those off us who aren't already well versed in configuring it, it's pretty hard to guess at what else it's expecting.

**Comment by ikr** [comment]
You can find the full nginx config file here https://github.com/ikr/annotator-store-lite/blob/master/salt/root/salt/nginx/server.conf
